# Generated by Django 4.1.5 on 2023-03-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
    ]
